#! /usr/bin/python
# Copyright 2015 Mark Haines
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import stoic.runner
import stoic.log
import argparse
import time
import logging
import os


logger = logging.getLogger("stoic")

stoic.log.console_handler()

parser = argparse.ArgumentParser()
parser.add_argument(
    "arguments", metavar="ARG", nargs='+', help="program arguments",
)
parser.add_argument(
    "--log-file", metavar="LOG_FILE",
    help="write logs to file, logs are rotated daily"
)

options = parser.parse_args()

if options.log_file is not None:
    log_file = os.path.abspath(options.log_file)
    logger.info("Writing logs to %r", log_file)
    stoic.log.rotating_file_handler(log_file, when="D", backupCount=10)

runner = stoic.runner.Runner("main", options.arguments)

runner.start()

try:
    while True:
        time.sleep(60 * 60 * 24)
except KeyboardInterrupt:
    pass
finally:
    runner.shutdown()
