#! /usr/bin/python
# Copyright 2015 Mark Haines
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import stoic.runner
import argparse
import time
import logging.config
import yaml


logging.config.dictConfig(yaml.load("""
version: 1
root:
  handlers:
  - console
  level: INFO
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    level: INFO
formatters:
  console:
    (): stoic.log.Iso8601Formatter
    format: '%(asctime)s|%(levelname)s|%(name)s|%(message)s'
"""))

parser = argparse.ArgumentParser()
parser.add_argument(
    "arguments", metavar="ARG", nargs='+', help="program arguments"
)
options = parser.parse_args()

runner = stoic.runner.Runner("main", options.arguments)

runner.start()

try:
    while True:
        time.sleep(60 * 60 * 24)
except KeyboardInterrupt:
    pass
finally:
    runner.shutdown()
